[tool.pylint.messages_control]
disable = [
    "no-member",
    "logging-fstring-interpolation",
    "too-many-instance-attributes",
    "too-many-arguments",
    "too-many-positional-arguments",
    "f-string-without-interpolation",
    "broad-exception-caught",
    "too-many-locals",
]

[tool.isort]
profile = "black"
line_length = 88
lines_after_imports = 2
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = [
    "--cov=src/batch",
    "--cov=src/model",
    "--cov-report=html",
    "--cov-report=term-missing",
]

filterwarnings = [
    "ignore::pytest.PytestDeprecationWarning",
    "ignore::FutureWarning:pandas",
    "ignore::FutureWarning"
]

[tool.coverage.run]
source = ["src"]
omit = [
    "src/model/run_pipeline.py"
]
